import { ThisReceiver } from '@angular/compiler';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ProductServiceService } from '../product-service.service';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})
export class ProductComponent implements OnInit {
  products=[{"id":1,"shop_name":"Movies","address":"3298 Sachs Parkway"},
  {"id":2,"shop_name":"Industrial","address":"5139 Stang Court"},
  {"id":3,"shop_name":"Electronics","address":"3 Starling Point"},
  {"id":4,"shop_name":"Industrial","address":"71 John Wall Way"},
  {"id":5,"shop_name":"Games","address":"8820 Kedzie Drive"},
  {"id":6,"shop_name":"Games","address":"51631 Vernon Plaza"},
  {"id":7,"shop_name":"Sports","address":"229 Moose Street"},
  {"id":8,"shop_name":"Tools","address":"3184 Moulton Street"},
  {"id":9,"shop_name":"Toys","address":"63931 Grasskamp Terrace"},
  {"id":10,"shop_name":"Grocery","address":"7 Katie Street"},
  {"id":11,"shop_name":"Outdoors","address":"845 Hanover Pass"},
  {"id":12,"shop_name":"Music","address":"67404 Del Sol Crossing"},
  {"id":13,"shop_name":"Shoes","address":"9 Ryan Street"},
  {"id":14,"shop_name":"Jewelry","address":"0 Mesta Junction"},
  {"id":15,"shop_name":"Books","address":"8116 Schlimgen Alley"},
  {"id":16,"shop_name":"Outdoors","address":"3 Anzinger Place"},
  {"id":17,"shop_name":"Automotive","address":"70 Fisk Terrace"},
  {"id":18,"shop_name":"Electronics","address":"55 Elmside Street"},
  {"id":19,"shop_name":"Computers","address":"127 Londonderry Road"},
  {"id":20,"shop_name":"Sports","address":"33075 Toban Alley"},
  {"id":21,"shop_name":"Movies","address":"0 Park Meadow Street"},
  {"id":22,"shop_name":"Jewelry","address":"168 Badeau Pass"},
  {"id":23,"shop_name":"Outdoors","address":"99 Grim Place"},
  {"id":24,"shop_name":"Clothing","address":"2 Maple Plaza"},
  {"id":25,"shop_name":"Jewelry","address":"87 Victoria Lane"},
  {"id":26,"shop_name":"Books","address":"68629 Vera Terrace"},
  {"id":27,"shop_name":"Games","address":"3 Carioca Trail"},
  {"id":28,"shop_name":"Games","address":"66606 Fuller Avenue"},
  {"id":29,"shop_name":"Jewelry","address":"07 Birchwood Place"},
  {"id":30,"shop_name":"Grocery","address":"448 Reinke Avenue"},
  {"id":31,"shop_name":"Computers","address":"1 Stephen Parkway"},
  {"id":32,"shop_name":"Home","address":"56 Johnson Crossing"},
  {"id":33,"shop_name":"Clothing","address":"7365 Longview Street"},
  {"id":34,"shop_name":"Jewelry","address":"8 Westerfield Point"},
  {"id":35,"shop_name":"Garden","address":"0 Bluejay Alley"},
  {"id":36,"shop_name":"Grocery","address":"831 Di Loreto Center"},
  {"id":37,"shop_name":"Sports","address":"93 Moland Point"},
  {"id":38,"shop_name":"Electronics","address":"4556 Scott Trail"},
  {"id":39,"shop_name":"Sports","address":"7262 Debs Parkway"},
  {"id":40,"shop_name":"Home","address":"2 Caliangt Court"},
  {"id":41,"shop_name":"Computers","address":"83 Kennedy Avenue"},
  {"id":42,"shop_name":"Garden","address":"3669 Sundown Alley"},
  {"id":43,"shop_name":"Health","address":"5524 Jana Drive"},
  {"id":44,"shop_name":"Kids","address":"377 Butterfield Point"},
  {"id":45,"shop_name":"Kids","address":"8629 Cambridge Circle"},
  {"id":46,"shop_name":"Automotive","address":"05 Stuart Lane"},
  {"id":47,"shop_name":"Garden","address":"9 Gale Road"},
  {"id":48,"shop_name":"Computers","address":"04 Hansons Place"},
  {"id":49,"shop_name":"Games","address":"87688 Caliangt Road"},
  {"id":50,"shop_name":"Books","address":"297 Derek Parkway"},
  {"id":51,"shop_name":"Tools","address":"11 Twin Pines Drive"},
  {"id":52,"shop_name":"Books","address":"47614 Redwing Court"},
  {"id":53,"shop_name":"Tools","address":"02275 Tony Center"},
  {"id":54,"shop_name":"Movies","address":"1 Farmco Plaza"},
  {"id":55,"shop_name":"Games","address":"2 Eagle Crest Plaza"},
  {"id":56,"shop_name":"Automotive","address":"99 Kingsford Road"},
  {"id":57,"shop_name":"Home","address":"5 Tennessee Circle"},
  {"id":58,"shop_name":"Outdoors","address":"2098 Lawn Court"},
  {"id":59,"shop_name":"Books","address":"404 Anzinger Court"},
  {"id":60,"shop_name":"Movies","address":"6843 Debra Drive"},
  {"id":61,"shop_name":"Sports","address":"60223 Pleasure Pass"},
  {"id":62,"shop_name":"Home","address":"528 Spaight Avenue"},
  {"id":63,"shop_name":"Home","address":"624 Browning Park"},
  {"id":64,"shop_name":"Games","address":"47 Cottonwood Lane"},
  {"id":65,"shop_name":"Health","address":"686 Spohn Hill"},
  {"id":66,"shop_name":"Movies","address":"9760 West Court"},
  {"id":67,"shop_name":"Electronics","address":"560 Dahle Hill"},
  {"id":68,"shop_name":"Health","address":"76079 Florence Street"},
  {"id":69,"shop_name":"Garden","address":"8 Carberry Way"},
  {"id":70,"shop_name":"Tools","address":"36064 Fieldstone Circle"},
  {"id":71,"shop_name":"Shoes","address":"6 Brickson Park Lane"},
  {"id":72,"shop_name":"Beauty","address":"1428 Northview Hill"},
  {"id":73,"shop_name":"Automotive","address":"8367 Northview Road"},
  {"id":74,"shop_name":"Music","address":"5136 Becker Center"},
  {"id":75,"shop_name":"Garden","address":"2849 Sundown Plaza"},
  {"id":76,"shop_name":"Outdoors","address":"099 Declaration Road"},
  {"id":77,"shop_name":"Books","address":"32 Alpine Plaza"},
  {"id":78,"shop_name":"Jewelry","address":"78 Sunnyside Trail"},
  {"id":79,"shop_name":"Electronics","address":"862 Cody Junction"},
  {"id":80,"shop_name":"Kids","address":"4 Acker Circle"},
  {"id":81,"shop_name":"Baby","address":"22 Merchant Parkway"},
  {"id":82,"shop_name":"Garden","address":"01 Ridgeway Drive"},
  {"id":83,"shop_name":"Health","address":"1880 Myrtle Plaza"},
  {"id":84,"shop_name":"Outdoors","address":"03073 Dayton Drive"},
  {"id":85,"shop_name":"Garden","address":"06 Waywood Park"},
  {"id":86,"shop_name":"Music","address":"27 Fair Oaks Pass"},
  {"id":87,"shop_name":"Outdoors","address":"8 Sullivan Pass"},
  {"id":88,"shop_name":"Books","address":"18965 Bonner Alley"},
  {"id":89,"shop_name":"Toys","address":"0338 High Crossing Trail"},
  {"id":90,"shop_name":"Industrial","address":"0 Sommers Pass"},
  {"id":91,"shop_name":"Outdoors","address":"6524 Moland Way"},
  {"id":92,"shop_name":"Baby","address":"35 Morrow Place"},
  {"id":93,"shop_name":"Kids","address":"54747 Transport Pass"},
  {"id":94,"shop_name":"Shoes","address":"29318 1st Road"},
  {"id":95,"shop_name":"Sports","address":"4 Waxwing Way"},
  {"id":96,"shop_name":"Grocery","address":"45 La Follette Avenue"},
  {"id":97,"shop_name":"Computers","address":"2 Banding Center"},
  {"id":98,"shop_name":"Home","address":"47331 Schlimgen Parkway"},
  {"id":99,"shop_name":"Toys","address":"700 Paget Park"},
  {"id":100,"shop_name":"Computers","address":"0119 Northridge Center"},
  {"id":101,"shop_name":"Computers","address":"048 Monica Point"},
  {"id":102,"shop_name":"Garden","address":"463 Mayfield Hill"},
  {"id":103,"shop_name":"Outdoors","address":"27848 Dottie Hill"},
  {"id":104,"shop_name":"Garden","address":"3870 Coleman Crossing"},
  {"id":105,"shop_name":"Jewelry","address":"9971 Barby Parkway"},
  {"id":106,"shop_name":"Home","address":"64683 Loeprich Crossing"},
  {"id":107,"shop_name":"Baby","address":"510 Stang Lane"},
  {"id":108,"shop_name":"Outdoors","address":"42435 Bonner Terrace"},
  {"id":109,"shop_name":"Outdoors","address":"4 Arrowood Alley"},
  {"id":110,"shop_name":"Baby","address":"21954 Norway Maple Street"},
  {"id":111,"shop_name":"Outdoors","address":"78411 Raven Crossing"},
  {"id":112,"shop_name":"Industrial","address":"66 Lakeland Trail"},
  {"id":113,"shop_name":"Kids","address":"186 Sommers Hill"},
  {"id":114,"shop_name":"Jewelry","address":"72442 Beilfuss Park"},
  {"id":115,"shop_name":"Games","address":"3870 Golden Leaf Avenue"},
  {"id":116,"shop_name":"Health","address":"525 Surrey Road"},
  {"id":117,"shop_name":"Beauty","address":"928 Walton Alley"},
  {"id":118,"shop_name":"Grocery","address":"21 Morning Junction"},
  {"id":119,"shop_name":"Outdoors","address":"6037 Lindbergh Trail"},
  {"id":120,"shop_name":"Beauty","address":"1 Becker Circle"},
  {"id":121,"shop_name":"Toys","address":"8715 Prairieview Parkway"},
  {"id":122,"shop_name":"Computers","address":"02 Namekagon Lane"},
  {"id":123,"shop_name":"Health","address":"72 Fairfield Trail"},
  {"id":124,"shop_name":"Health","address":"5 Bashford Road"},
  {"id":125,"shop_name":"Health","address":"9 Mariners Cove Park"},
  {"id":126,"shop_name":"Garden","address":"91 Arapahoe Circle"},
  {"id":127,"shop_name":"Electronics","address":"8672 2nd Point"},
  {"id":128,"shop_name":"Kids","address":"67004 Anzinger Terrace"},
  {"id":129,"shop_name":"Clothing","address":"1 East Court"},
  {"id":130,"shop_name":"Toys","address":"558 Fallview Park"},
  {"id":131,"shop_name":"Games","address":"14 Carey Center"},
  {"id":132,"shop_name":"Kids","address":"1 Westend Avenue"},
  {"id":133,"shop_name":"Books","address":"021 Hansons Circle"},
  {"id":134,"shop_name":"Toys","address":"22 Helena Drive"},
  {"id":135,"shop_name":"Jewelry","address":"547 Vernon Way"},
  {"id":136,"shop_name":"Grocery","address":"4 Almo Park"},
  {"id":137,"shop_name":"Home","address":"3896 South Avenue"},
  {"id":138,"shop_name":"Computers","address":"34 Erie Circle"},
  {"id":139,"shop_name":"Toys","address":"0568 Loftsgordon Trail"},
  {"id":140,"shop_name":"Computers","address":"8 Kensington Trail"},
  {"id":141,"shop_name":"Electronics","address":"0599 Pierstorff Terrace"},
  {"id":142,"shop_name":"Health","address":"02436 Thackeray Junction"},
  {"id":143,"shop_name":"Games","address":"3 Golden Leaf Lane"},
  {"id":144,"shop_name":"Grocery","address":"5040 Kedzie Place"},
  {"id":145,"shop_name":"Movies","address":"43849 6th Place"},
  {"id":146,"shop_name":"Computers","address":"571 Fallview Court"},
  {"id":147,"shop_name":"Outdoors","address":"3 Monterey Point"},
  {"id":148,"shop_name":"Outdoors","address":"866 Holmberg Lane"},
  {"id":149,"shop_name":"Shoes","address":"465 Manley Terrace"},
  {"id":150,"shop_name":"Health","address":"88 Bunker Hill Hill"},
  {"id":151,"shop_name":"Automotive","address":"2654 Fuller Crossing"},
  {"id":152,"shop_name":"Garden","address":"304 Hauk Court"},
  {"id":153,"shop_name":"Industrial","address":"37 Acker Trail"},
  {"id":154,"shop_name":"Books","address":"6023 New Castle Drive"},
  {"id":155,"shop_name":"Sports","address":"51 Manley Circle"},
  {"id":156,"shop_name":"Kids","address":"38 Logan Circle"},
  {"id":157,"shop_name":"Shoes","address":"31978 Hollow Ridge Plaza"},
  {"id":158,"shop_name":"Tools","address":"5 Sunnyside Lane"},
  {"id":159,"shop_name":"Games","address":"26 Eastlawn Crossing"},
  {"id":160,"shop_name":"Computers","address":"92 Pierstorff Avenue"},
  {"id":161,"shop_name":"Books","address":"037 Mallory Plaza"},
  {"id":162,"shop_name":"Books","address":"70 Manley Parkway"},
  {"id":163,"shop_name":"Industrial","address":"803 West Court"},
  {"id":164,"shop_name":"Automotive","address":"5027 Anzinger Drive"},
  {"id":165,"shop_name":"Shoes","address":"0 Sullivan Junction"},
  {"id":166,"shop_name":"Shoes","address":"65 Pepper Wood Terrace"},
  {"id":167,"shop_name":"Computers","address":"02 Artisan Crossing"},
  {"id":168,"shop_name":"Movies","address":"434 Union Park"},
  {"id":169,"shop_name":"Computers","address":"58706 Porter Pass"},
  {"id":170,"shop_name":"Grocery","address":"6892 Dixon Terrace"},
  {"id":171,"shop_name":"Toys","address":"292 Morningstar Way"},
  {"id":172,"shop_name":"Computers","address":"18 Rigney Crossing"},
  {"id":173,"shop_name":"Garden","address":"550 Logan Avenue"},
  {"id":174,"shop_name":"Music","address":"2 Gale Park"},
  {"id":175,"shop_name":"Automotive","address":"592 Farragut Point"},
  {"id":176,"shop_name":"Automotive","address":"552 Hudson Road"},
  {"id":177,"shop_name":"Tools","address":"374 Sycamore Trail"},
  {"id":178,"shop_name":"Industrial","address":"20263 Basil Junction"},
  {"id":179,"shop_name":"Kids","address":"735 Stoughton Avenue"},
  {"id":180,"shop_name":"Movies","address":"1 Westend Center"},
  {"id":181,"shop_name":"Electronics","address":"870 Lien Terrace"},
  {"id":182,"shop_name":"Electronics","address":"2740 Lerdahl Crossing"},
  {"id":183,"shop_name":"Automotive","address":"84468 Quincy Court"},
  {"id":184,"shop_name":"Kids","address":"178 Bellgrove Trail"},
  {"id":185,"shop_name":"Home","address":"275 Grover Drive"},
  {"id":186,"shop_name":"Games","address":"58107 Jenifer Parkway"},
  {"id":187,"shop_name":"Computers","address":"0000 Amoth Lane"},
  {"id":188,"shop_name":"Jewelry","address":"1933 Warbler Road"},
  {"id":189,"shop_name":"Tools","address":"6158 Eggendart Trail"},
  {"id":190,"shop_name":"Grocery","address":"3314 Forest Parkway"},
  {"id":191,"shop_name":"Health","address":"83066 Cody Drive"},
  {"id":192,"shop_name":"Grocery","address":"96 Tony Street"},
  {"id":193,"shop_name":"Music","address":"42864 Loeprich Plaza"},
  {"id":194,"shop_name":"Sports","address":"667 Hanson Trail"},
  {"id":195,"shop_name":"Tools","address":"572 Merrick Lane"},
  {"id":196,"shop_name":"Games","address":"33 Village Point"},
  {"id":197,"shop_name":"Beauty","address":"60947 Westport Court"},
  {"id":198,"shop_name":"Beauty","address":"2 Artisan Pass"},
  {"id":199,"shop_name":"Health","address":"5 Kim Way"},
  {"id":200,"shop_name":"Outdoors","address":"67 Corscot Point"}]

  constructor(private router :Router,private service:ProductServiceService) { }

  ngOnInit(): void {
    
  }
  

  onSelect(product){

    console.log("product",product.id)
    this.router.navigate(['/product',product.id])
    this.service.setData(product)


  }
}
